# Generated by Django 6.1 on 2026-08-21 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('image', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=300)),
                ('fabriquant', models.CharField(max_length=300)),
                ('modele', models.CharField(max_length=300)),
                ('localisation', models.CharField(max_length=300)),
                ('snmp', models.CharField(max_length=300)),
                ('snmp_port', models.ImageField(upload_to='')),
                ('snmp_version', models.CharField(max_length=300)),
                ('uptime', models.DurationField(help_text='temps ecoulé depuis le dernier demarrage')),
                ('statut', models.BooleanField(default=False)),
                ('cpu', models.IntegerField()),
                ('memoire', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('latence', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_equipements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
