# Generated by Django 6.1 on 2026-08-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipements',
            name='image',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='equipements',
            name='snmp_port',
            field=models.IntegerField(),
        ),
    ]
